version: "3.6"

services:
    citdb:
        image: docker.io/postgres:15.1-alpine
        container_name: 'cit_db'
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes: 
            - /opt/citdb/volumes/pgdb:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} "]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always
        networks:
            - cit-api-net

    citapi:
        build: .
        container_name: 'cit_api'
        env_file:
            - .env
        environment:
            - DB_ENGINE=${DB_ENGINE}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=citdb
            - DB_PORT=${DB_PORT}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - EMAIL_PORT=${EMAIL_PORT}

        command: > 
            bash -c
            "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py init_admin &&
             python manage.py runserver 0.0.0.0:8888 &&
             gunicorn --bind 0.0.0.0:8888 CIT_STAFF.wsgi -w 40 -k uvicorn.workers.UvicornWorker"
        ports: 
            - "8888:8888"
        depends_on:
            - citdb
        restart: always
        volumes:
            - /opt/citapi/volumes/api/media:/CITAPI/cit_media
        networks:
            - cit-api-net

networks:
    cit-api-net:
        driver: bridge